[package]
name = "actix-admin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version="4", default-features = false, features = ["macros"]}
tracing-actix-web = "0.7.10"
tracing = "0.1"
futures-util = "0.3.25"

json = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.18.1", features = ["derive"] }

log = "0.4"
log4rs = "1.0"
#env_logger = "0.9"

rbs = { version = "4.5"}
rbatis = { version = "4.5"}
#rbatis = { version = "4.0",features = ["debug_mode"]}
rbdc-mysql={version="4.5"}

jsonwebtoken = "9.3.0"

redis = "0.25.3"

futures = { version = "0.3", default-features = false }
thiserror = "1.0"