//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use crate::model::system::sys_menu::Entity as SysMenu;
pub use crate::model::system::sys_role::Entity as SysRole;
pub use crate::model::system::sys_role_menu::Entity as SysRoleMenu;
pub use crate::model::system::sys_user::Entity as SysUser;
pub use crate::model::system::sys_user_role::Entity as SysUserRole;

