refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{f}:{L}] {h({l})} [{M}] - {m}{n}"
  file:
    kind: rolling_file
    path: "log/ntex-admin.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{f}:{L}] {h({l})} [{M}] - {m}{n}"
    #      kind: json
    policy:
      #trigger:
      #  kind: size
      #  limit: 10 mb  #测试日志轮转，可以改成1 kb
      trigger:
        kind: time
        interval: 1 day
      roller:
        kind: fixed_window
        pattern: "log/old-ntex-admin-{}.log"
        base: 1
        count: 30
root:
  level: debug
  appenders:
    - stdout
    - file